addons:
  firefox: latest
language: python
python:
  - '3.8'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

env: ENV='staging'

services:
  - postgresql

script:
  - ./manage.py test
