# Generated by Django 3.2.4 on 2021-06-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210623_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('is_full', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.slot'),
            preserve_default=False,
        ),
    ]
