# Generated by Django 3.2.4 on 2021-07-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20210719_1040'),
        ('booking', '0003_auto_20210628_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Réservation'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Période'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['day'], 'verbose_name': 'Créneau', 'verbose_name_plural': 'Créneaux'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='registration.child', verbose_name='Enfant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='whole',
            field=models.BooleanField(default=True, verbose_name='Journée complète'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='day',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Complet'),
        ),
    ]
