# Generated by Django 3.2.4 on 2021-08-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20210806_1151'),
        ('booking', '0006_auto_20210721_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': "Période d'ouverture", 'verbose_name_plural': "Périodes d'ouverture"},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['day'], 'verbose_name': 'Jour'},
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('start_time', models.TimeField(verbose_name='Heure début')),
                ('end_time', models.TimeField(verbose_name='Heure fin')),
                ('extra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Supplément tarif')),
                ('categories', models.ManyToManyField(related_name='activities', to='registration.Category', verbose_name='Catégorie')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='booking.slot', verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Activité',
                'ordering': ['start_time'],
            },
        ),
    ]
