# Generated by Django 3.2.4 on 2021-06-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210614_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='authorized_person',
        ),
        migrations.RemoveField(
            model_name='child',
            name='doctor',
        ),
        migrations.AddField(
            model_name='family',
            name='authorized_person',
            field=models.ManyToManyField(blank=True, related_name='authorized_person', to='registration.Adult'),
        ),
        migrations.AddField(
            model_name='family',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='registration.adult'),
        ),
    ]
