# Generated by Django 3.2.4 on 2021-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210614_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
