# Generated by Django 3.2.4 on 2021-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_adult_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='beneficiary_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='beneficiary_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='insurance_name',
            field=models.CharField(default='NC', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='insurance_number',
            field=models.CharField(default='000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='plan',
            field=models.CharField(default='CAF', max_length=50),
            preserve_default=False,
        ),
    ]
