# Generated by Django 3.2.4 on 2021-06-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20210614_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='legal_guardian_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lg1', to='registration.adult'),
        ),
        migrations.AlterField(
            model_name='child',
            name='legal_guardian_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lg2', to='registration.adult'),
        ),
        migrations.AlterField(
            model_name='family',
            name='authorized_person',
            field=models.ManyToManyField(blank=True, related_name='family_friends', to='registration.Adult'),
        ),
        migrations.AlterField(
            model_name='family',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_doctor', to='registration.adult'),
        ),
    ]
