# Generated by Django 3.2.4 on 2021-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20210615_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='job_address',
        ),
        migrations.AlterField(
            model_name='adult',
            name='family_situation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='job_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='go_alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='beneficiary_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
