# Generated by Django 3.2.4 on 2021-07-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20210617_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adult',
            options={'verbose_name': 'Adulte'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Enfant'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Famille'},
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
