# Generated by Django 3.2.4 on 2021-07-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20210719_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
