# Generated by Django 3.2.4 on 2021-07-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_family_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='cell_phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Tél portable'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='family_situation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situation familiale'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='job_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tél travail'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='child',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='Toutes activités'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.family', verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='child',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='child',
            name='go_alone',
            field=models.BooleanField(default=False, verbose_name='Part seul'),
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='child',
            name='image_rights',
            field=models.BooleanField(default=True, verbose_name='Droits communication'),
        ),
        migrations.AlterField(
            model_name='child',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Informations'),
        ),
        migrations.AlterField(
            model_name='child',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='child',
            name='legal_guardian_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lg1', to='registration.adult', verbose_name='Représentant légal 1'),
        ),
        migrations.AlterField(
            model_name='child',
            name='legal_guardian_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lg2', to='registration.adult', verbose_name='Représentant légal 2'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ecole'),
        ),
        migrations.AlterField(
            model_name='family',
            name='authorized_person',
            field=models.ManyToManyField(blank=True, related_name='family_friends', to='registration.Adult', verbose_name='Personnes autorisées a récupérer les enfants'),
        ),
        migrations.AlterField(
            model_name='family',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom allocataire'),
        ),
        migrations.AlterField(
            model_name='family',
            name='beneficiary_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° allocataire'),
        ),
        migrations.AlterField(
            model_name='family',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_doctor', to='registration.adult', verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='family',
            name='home_address',
            field=models.CharField(max_length=100, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='family',
            name='home_phone',
            field=models.CharField(max_length=10, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='family',
            name='insurance_name',
            field=models.CharField(max_length=50, verbose_name='Assurance'),
        ),
        migrations.AlterField(
            model_name='family',
            name='insurance_number',
            field=models.CharField(max_length=50, verbose_name='N° police'),
        ),
        migrations.AlterField(
            model_name='family',
            name='plan',
            field=models.CharField(max_length=50, verbose_name="Régime d'appartenance"),
        ),
        migrations.AlterField(
            model_name='family',
            name='use_name',
            field=models.CharField(max_length=50, verbose_name="Nom d'usage"),
        ),
        migrations.AlterField(
            model_name='family',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
