# Generated by Django 3.2.4 on 2021-07-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210720_1456'),
        ('registration', '0017_auto_20210720_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.category', verbose_name='Catégorie'),
        ),
    ]
