# Generated by Django 3.2.4 on 2021-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_child_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('family', 'firstname', 'lastname'), name='unique_child'),
        ),
    ]
