# Generated by Django 3.2.4 on 2021-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_quotient', models.CharField(max_length=15)),
                ('day', models.DecimalField(decimal_places=2, max_digits=4)),
                ('half_day', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
