# Generated by Django 3.2.4 on 2021-06-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210618_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['entry']},
        ),
    ]
