# Generated by Django 3.2.4 on 2021-07-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210622_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_time'], 'verbose_name': 'Activité'},
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['entry'], 'verbose_name': "Entrée de l'agenda", 'verbose_name_plural': "Entrées de l'agenda"},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['day'], 'verbose_name': 'Tarif'},
        ),
    ]
