# Generated by Django 3.2.4 on 2021-07-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210719_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['entry'], 'verbose_name': "Page de l'agenda", 'verbose_name_plural': "Pages de l'agenda"},
        ),
        migrations.AddField(
            model_name='category',
            name='age_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='age_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(related_name='activities', to='home.Category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='home.agenda', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(verbose_name='Heure fin'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(verbose_name='Heure début'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='entry',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='price',
            name='day',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prix journée'),
        ),
        migrations.AlterField(
            model_name='price',
            name='family_quotient',
            field=models.CharField(max_length=15, verbose_name='Quotient familial'),
        ),
        migrations.AlterField(
            model_name='price',
            name='half_day',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prix demi-journée'),
        ),
    ]
