# Generated by Django 3.2.4 on 2021-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210721_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='extra_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Supplément tarif'),
        ),
    ]
