# Generated by Django 3.2.4 on 2021-08-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_activity_extra_charge'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category',
        ),
    ]
