# Generated by Django 3.2.4 on 2021-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20210806_1151'),
        ('home', '0008_remove_category_unique_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(related_name='activities', to='registration.Category', verbose_name='Catégorie'),
        ),
    ]
