# Generated by Django 3.2.4 on 2021-08-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210721_1541'),
        ('home', '0009_auto_20210806_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.AddField(
            model_name='activity',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='booking.slot', verbose_name='Date'),
        ),
    ]
